### PR TITLE
change base image from debian 11 to debian 12

### PR DESCRIPTION
**Pull request by jenkoon**
**Description of the change**

CVE FIX
https://github.com/milvus-io/milvus/issues/34520

**Benefits**

FIX 6 HIGH/CRITICAL CVEs of etcd base image

- bitnami/minideb:bookworm (debian 12.6)
Total: 5 (HIGH: 4, CRITICAL: 1)

- bitnami/minideb:bullseye (debian 11.10)
Total: 12 (HIGH: 10, CRITICAL: 2)

### CODE REVIEW

**Comment by jenkoon** [comment]
@haorenfsa please review, thanks

**Comment by jenkoon** [comment]
@LoveEachDay please review, thanks.

**Review by haorenfsa — APPROVED** [review]

**Comment by jenkoon** [comment]
#8 0.051 /bin/bash: line 1: /usr/sbin/install_packages: Permission denied
#8 ERROR: process "/bin/bash -o pipefail -c install_packages ca-certificates curl procps" did not complete successfully: exit code: 126

Permission denied??

**Comment by haorenfsa** [comment]
em....  I'm checking how bitnami's newest dockerfile
https://github.com/bitnami/containers/blob/main/bitnami/etcd/3.5/debian-12/Dockerfile

**Comment by jenkoon** [comment]
Why don't we use the original bitnami etcd?

**Comment by haorenfsa** [comment]
https://github.com/milvus-io/bitnami-docker-etcd?tab=readme-ov-file#why-we-forked-this-repo

**Comment by jenkoon** [comment]
what is the status?

**Pull request merged**
